[build-system]
requires = [
    "setuptools==68.2.2",
    "wheel"
]
build-backend = "setuptools.build_meta"

[project]
name = "wikiloader"
version = "0.1.0"
dependencies = [
    "requests>=2.22.0",
    "sentencepiece>=0.1.97",
    "fasttext>=0.9.2",
    "scipy>=1.10.1",
    "nltk",
]

